In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('data/zomato.csv',thousands=',')
print("Shape:",df.shape)
df.head()

Shape: (51717, 17)

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800.0,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800.0,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800.0,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300.0,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600.0,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [2]:
print(df.info)
print("\nNull values:\n", df.isnull().sum())
print("\nColumns names:", df.columns.tolist())

<bound method DataFrame.info of                                                      url  \
0      https://www.zomato.com/bangalore/jalsa-banasha...
1      https://www.zomato.com/bangalore/spice-elephan...
2      https://www.zomato.com/SanchurroBangalore?cont...
3      https://www.zomato.com/bangalore/addhuri-udupi...
4      https://www.zomato.com/bangalore/grand-village...
...                                                  ...
51712  https://www.zomato.com/bangalore/best-brews-fo...
51713  https://www.zomato.com/bangalore/vinod-bar-and...
51714  https://www.zomato.com/bangalore/plunge-sherat...
51715  https://www.zomato.com/bangalore/chime-sherato...
51716  https://www.zomato.com/bangalore/the-nest-the-...

                                                 address  \
0      942, 21st Main Road, 2nd Stage, Banashankari, ...
1      2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...
2      1112, Next to KIMS Medical College, 17th Cross...
3      1st Floor, Annakuteera, 3rd Stage, Banashankar...
4      10, 3rd Floor, Lakshmi Associates, Gandhi Baza...
...                                                  ...
51712  Four Points by Sheraton Bengaluru, 43/3, White...
51713  Number 10, Garudachar Palya, Mahadevapura, Whi...
51714  Sheraton Grand Bengaluru Whitefield Hotel & Co...
51715  Sheraton Grand Bengaluru Whitefield Hotel & Co...
51716  ITPL Main Road, KIADB Export Promotion Industr...

                                                    name online_order  \
0                                                  Jalsa          Yes
1                                         Spice Elephant          Yes
2                                        San Churro Cafe          Yes
3                                  Addhuri Udupi Bhojana           No
4                                          Grand Village           No
...                                                  ...          ...
51712  Best Brews - Four Points by Sheraton Bengaluru...           No
51713                           Vinod Bar And Restaurant           No
51714  Plunge - Sheraton Grand Bengaluru Whitefield H...           No
51715  Chime - Sheraton Grand Bengaluru Whitefield Ho...           No
51716                       The Nest - The Den Bengaluru           No

      book_table    rate  votes                             phone  \
0            Yes   4.1/5    775    080 42297555\r\n+91 9743772233
1             No   4.1/5    787                      080 41714161
2             No   3.8/5    918                    +91 9663487993
3             No   3.7/5     88                    +91 9620009302
4             No   3.8/5    166  +91 8026612447\r\n+91 9901210005
...          ...     ...    ...                               ...
51712         No  3.6 /5     27                      080 40301477
51713         No     NaN      0                    +91 8197675843
51714         No     NaN      0                               NaN
51715        Yes  4.3 /5    236                      080 49652769
51716         No  3.4 /5     13                    +91 8071117272

                         location            rest_type  \
0                    Banashankari        Casual Dining
1                    Banashankari        Casual Dining
2                    Banashankari  Cafe, Casual Dining
3                    Banashankari          Quick Bites
4                    Basavanagudi        Casual Dining
...                           ...                  ...
51712                  Whitefield                  Bar
51713                  Whitefield                  Bar
51714                  Whitefield                  Bar
51715  ITPL Main Road, Whitefield                  Bar
51716  ITPL Main Road, Whitefield   Bar, Casual Dining

                                              dish_liked  \
0      Pasta, Lunch Buffet, Masala Papad, Paneer Laja...
1      Momos, Lunch Buffet, Chocolate Nirvana, Thai G...
2      Churros, Cannelloni, Minestrone Soup, Hot Choc...
3                                            Masala Dosa
4                                    Panipuri, Gol Gappe
...                                                  ...
51712                                                NaN
51713                                                NaN
51714                                                NaN
51715                       Cocktails, Pizza, Buttermilk
51716                                                NaN

                                     cuisines  approx_cost(for two people)  \
0              North Indian, Mughlai, Chinese                        800.0
1                 Chinese, North Indian, Thai                        800.0
2                      Cafe, Mexican, Italian                        800.0
3                  South Indian, North Indian                        300.0
4                    North Indian, Rajasthani                        600.0
...                                       ...                          ...
51712                             Continental                       1500.0
51713                             Finger Food                        600.0
51714                             Finger Food                       2000.0
51715                             Finger Food                       2500.0
51716  Finger Food, North Indian, Continental                       1500.0

                                            reviews_list menu_item  \
0      [('Rated 4.0', 'RATED\n  A beautiful place to ...        []
1      [('Rated 4.0', 'RATED\n  Had been here for din...        []
2      [('Rated 3.0', "RATED\n  Ambience is not that ...        []
3      [('Rated 4.0', "RATED\n  Great food and proper...        []
4      [('Rated 4.0', 'RATED\n  Very good restaurant ...        []
...                                                  ...       ...
51712  [('Rated 5.0', "RATED\n  Food and service are ...        []
51713                                                 []        []
51714                                                 []        []
51715  [('Rated 4.0', 'RATED\n  Nice and friendly pla...        []
51716  [('Rated 5.0', 'RATED\n  Great ambience , look...        []

      listed_in(type) listed_in(city)
0              Buffet    Banashankari
1              Buffet    Banashankari
2              Buffet    Banashankari
3              Buffet    Banashankari
4              Buffet    Banashankari
...               ...             ...
51712   Pubs and bars      Whitefield
51713   Pubs and bars      Whitefield
51714   Pubs and bars      Whitefield
51715   Pubs and bars      Whitefield
51716   Pubs and bars      Whitefield

[51717 rows x 17 columns]>

Null values:
 url                                0
address                            0
name                               0
online_order                       0
book_table                         0
rate                            7775
votes                              0
phone                           1208
location                          21
rest_type                        227
dish_liked                     28078
cuisines                          45
approx_cost(for two people)      346
reviews_list                       0
menu_item                          0
listed_in(type)                    0
listed_in(city)                    0
dtype: int64

Columns names: ['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes', 'phone', 'location', 'rest_type', 'dish_liked', 'cuisines', 'approx_cost(for two people)', 'reviews_list', 'menu_item', 'listed_in(type)', 'listed_in(city)']

In [3]:
df.columns=[
    'url', 'address', 'name','online_order', 'book_table',
    'rate', 'votes', 'phone', 'location', 'rest_type', 
    'dish_liked', 'cuisines','cost_for_two', 'reviews_list',
    'menu_item', 'listed_type', 'listed_city'
]

In [4]:
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,cost_for_two,reviews_list,menu_item,listed_type,listed_city
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800.0,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800.0,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8/5,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800.0,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7/5,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300.0,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8/5,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600.0,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [5]:
df['rate']=df['rate'].astype(str).str.replace('/5','', regex=False).str.strip()
df['rate']=df['rate'].replace(['NEW','-', 'nan'],np.nan)
df['rate']=pd.to_numeric(df['rate'], errors='coerce')

print("Rating range:", df['rate'].min(),"to", df['rate'].max())
print("Nulls in rate:", df['rate'].isnull().sum())

Rating range: 1.8 to 4.9
Nulls in rate: 10052

In [6]:
print("Restaurants with ratings:", df['rate'].notna().sum())
print("Restaurants with ratings:", df['rate'].isna().sum())

Restaurants with ratings: 41665
Restaurants with ratings: 10052

In [7]:
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,cost_for_two,reviews_list,menu_item,listed_type,listed_city
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800.0,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800.0,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800.0,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300.0,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600.0,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [8]:
df['cost_for_two']=df['cost_for_two'].astype(str).str.replace(',','', regex=False)
df['cost_for_two']=pd.to_numeric(df['cost_for_two'], errors='coerce')

print("Cost range: Rs.", df['cost_for_two'].min(), "to Rs.", df['cost_for_two'].max())
print("Nulls in cost:", df['cost_for_two'].isnull().sum())

Cost range: Rs. 40.0 to Rs. 6000.0
Nulls in cost: 346

In [9]:
median_cost=df['cost_for_two'].median()
df['cost_for_two'].fillna(median_cost, inplace=True)

print("Nulls after fill:", df['cost_for_two'].isnull().sum())
print("Median cost used: Rs.", median_cost)

Nulls after fill: 0
Median cost used: Rs. 400.0

C:\Users\KIIT\AppData\Local\Temp\ipykernel_26116\1409212667.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['cost_for_two'].fillna(median_cost, inplace=True)

In [10]:
df.head(5)

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,cost_for_two,reviews_list,menu_item,listed_type,listed_city
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800.0,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800.0,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,Yes,No,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800.0,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,No,No,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300.0,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,No,No,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600.0,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari

In [11]:
df['online_order']=df['online_order'].map({'Yes':1,'No':0})
df['book_table']=df['book_table'].map({'Yes':1,'No':0})
df['votes']=pd.to_numeric(df['votes'], errors='coerce').fillna(0).astype(int)

print("Online order values:", df['online_order'].unique())
print("Book table values:", df['book_table'].unique())
print("Votes range:",df['votes'].min(), "to", df['votes'].max())

Online order values: [1 0]
Book table values: [1 0]
Votes range: 0 to 16832

In [12]:
df.dropna(subset=['name', 'location'], inplace= True)
print("Shape after dropping essential nulls:", df.shape)

Shape after dropping essential nulls: (51696, 17)

In [13]:
df['cuisine_count']=df['cuisines'].dropna().apply(lambda x: len(x.split(',')))
df['primary_cuisine']=df['cuisines'].dropna().apply(lambda x: x.split(',')[0].strip())

df[['name','cuisines','primary_cuisine','cuisine_count']].head(10)

,name,cuisines,primary_cuisine,cuisine_count
0,Jalsa,"North Indian, Mughlai, Chinese",North Indian,3.0
1,Spice Elephant,"Chinese, North Indian, Thai",Chinese,3.0
2,San Churro Cafe,"Cafe, Mexican, Italian",Cafe,3.0
3,Addhuri Udupi Bhojana,"South Indian, North Indian",South Indian,2.0
4,Grand Village,"North Indian, Rajasthani",North Indian,2.0
5,Timepass Dinner,North Indian,North Indian,1.0
6,Rosewood International Hotel - Bar & Restaurant,"North Indian, South Indian, Andhra, Chinese",North Indian,4.0
7,Onesta,"Pizza, Cafe, Italian",Pizza,3.0
8,Penthouse Cafe,"Cafe, Italian, Continental",Cafe,3.0
9,Smacznego,"Cafe, Mexican, Italian, Momos, Beverages",Cafe,5.0

In [14]:
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,cost_for_two,reviews_list,menu_item,listed_type,listed_city,cuisine_count,primary_cuisine
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,1,1,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800.0,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,3.0,North Indian
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,1,0,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800.0,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,3.0,Chinese
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,1,0,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800.0,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,3.0,Cafe
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,0,0,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300.0,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,2.0,South Indian
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,0,0,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600.0,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,2.0,North Indian

In [15]:
print(df.columns.tolist())

['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes', 'phone', 'location', 'rest_type', 'dish_liked', 'cuisines', 'cost_for_two', 'reviews_list', 'menu_item', 'listed_type', 'listed_city', 'cuisine_count', 'primary_cuisine']

In [16]:
df.iloc[0]

url                https://www.zomato.com/bangalore/jalsa-banasha...
address            942, 21st Main Road, 2nd Stage, Banashankari, ...
name                                                           Jalsa
online_order                                                       1
book_table                                                         1
rate                                                             4.1
votes                                                            775
phone                                 080 42297555\r\n+91 9743772233
location                                                Banashankari
rest_type                                              Casual Dining
dish_liked         Pasta, Lunch Buffet, Masala Papad, Paneer Laja...
cuisines                              North Indian, Mughlai, Chinese
cost_for_two                                                   800.0
reviews_list       [('Rated 4.0', 'RATED\n  A beautiful place to ...
menu_item                                                         []
listed_type                                                   Buffet
listed_city                                             Banashankari
cuisine_count                                                    3.0
primary_cuisine                                         North Indian
Name: 0, dtype: object

In [17]:

df_raw = pd.read_csv('data/zomato.csv', thousands=',')
print(df_raw.columns.tolist())
df_raw.head(2)

['url', 'address', 'name', 'online_order', 'book_table', 'rate', 'votes', 'phone', 'location', 'rest_type', 'dish_liked', 'cuisines', 'approx_cost(for two people)', 'reviews_list', 'menu_item', 'listed_in(type)', 'listed_in(city)']

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,approx_cost(for two people),reviews_list,menu_item,listed_in(type),listed_in(city)
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,Yes,Yes,4.1/5,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800.0,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,Yes,No,4.1/5,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800.0,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari

In [18]:
df_raw = pd.read_csv('data/zomato.csv', thousands=',')
print("Original columns:")
for i, col in enumerate(df_raw.columns.tolist()):
    print(f"{i}: {col}")

Original columns:
0: url
1: address
2: name
3: online_order
4: book_table
5: rate
6: votes
7: phone
8: location
9: rest_type
10: dish_liked
11: cuisines
12: approx_cost(for two people)
13: reviews_list
14: menu_item
15: listed_in(type)
16: listed_in(city)

In [19]:
df.head()

,url,address,name,online_order,book_table,rate,votes,phone,location,rest_type,dish_liked,cuisines,cost_for_two,reviews_list,menu_item,listed_type,listed_city,cuisine_count,primary_cuisine
0,https://www.zomato.com/bangalore/jalsa-banasha...,"942, 21st Main Road, 2nd Stage, Banashankari, ...",Jalsa,1,1,4.1,775,080 42297555\r\n+91 9743772233,Banashankari,Casual Dining,"Pasta, Lunch Buffet, Masala Papad, Paneer Laja...","North Indian, Mughlai, Chinese",800.0,"[('Rated 4.0', 'RATED\n A beautiful place to ...",[],Buffet,Banashankari,3.0,North Indian
1,https://www.zomato.com/bangalore/spice-elephan...,"2nd Floor, 80 Feet Road, Near Big Bazaar, 6th ...",Spice Elephant,1,0,4.1,787,080 41714161,Banashankari,Casual Dining,"Momos, Lunch Buffet, Chocolate Nirvana, Thai G...","Chinese, North Indian, Thai",800.0,"[('Rated 4.0', 'RATED\n Had been here for din...",[],Buffet,Banashankari,3.0,Chinese
2,https://www.zomato.com/SanchurroBangalore?cont...,"1112, Next to KIMS Medical College, 17th Cross...",San Churro Cafe,1,0,3.8,918,+91 9663487993,Banashankari,"Cafe, Casual Dining","Churros, Cannelloni, Minestrone Soup, Hot Choc...","Cafe, Mexican, Italian",800.0,"[('Rated 3.0', ""RATED\n Ambience is not that ...",[],Buffet,Banashankari,3.0,Cafe
3,https://www.zomato.com/bangalore/addhuri-udupi...,"1st Floor, Annakuteera, 3rd Stage, Banashankar...",Addhuri Udupi Bhojana,0,0,3.7,88,+91 9620009302,Banashankari,Quick Bites,Masala Dosa,"South Indian, North Indian",300.0,"[('Rated 4.0', ""RATED\n Great food and proper...",[],Buffet,Banashankari,2.0,South Indian
4,https://www.zomato.com/bangalore/grand-village...,"10, 3rd Floor, Lakshmi Associates, Gandhi Baza...",Grand Village,0,0,3.8,166,+91 8026612447\r\n+91 9901210005,Basavanagudi,Casual Dining,"Panipuri, Gol Gappe","North Indian, Rajasthani",600.0,"[('Rated 4.0', 'RATED\n Very good restaurant ...",[],Buffet,Banashankari,2.0,North Indian

In [20]:
print("Final shape:", df.shape)
print("\nNull values remaining:\n", df.isnull().sum())

Final shape: (51696, 19)

Null values remaining:
 url                    0
address                0
name                   0
online_order           0
book_table             0
rate               10031
votes                  0
phone               1187
location               0
rest_type            206
dish_liked         28057
cuisines              24
cost_for_two           0
reviews_list           0
menu_item              0
listed_type            0
listed_city            0
cuisine_count         24
primary_cuisine       24
dtype: int64

In [22]:
df['rest_type'].fillna('Unknown', inplace=True)

df['cuisines'].fillna('Unknown', inplace= True)
df['primary_cuisine'].fillna('Unknown', inplace= True)
df['cuisine_count'].fillna(0, inplace= True)

print("Nulls remaining:\n", df.isnull().sum())

Nulls remaining:
 url                    0
address                0
name                   0
online_order           0
book_table             0
rate               10031
votes                  0
phone               1187
location               0
rest_type              0
dish_liked         28057
cuisines               0
cost_for_two           0
reviews_list           0
menu_item              0
listed_type            0
listed_city            0
cuisine_count          0
primary_cuisine        0
dtype: int64

C:\Users\KIIT\AppData\Local\Temp\ipykernel_26116\2473718600.py:4: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['primary_cuisine'].fillna('Unknown', inplace= True)
C:\Users\KIIT\AppData\Local\Temp\ipykernel_26116\2473718600.py:5: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['cuisine_count'].fillna(0, inplace= True)

In [23]:
df.to_csv('data/zomato_clean.csv', index=False)
print("Clean data saved-shape:",df.shape)

Clean data saved-shape: (51696, 19)